-- Create community table
CREATE TABLE community (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           active BOOLEAN NOT NULL,
                           description TEXT,
                           address VARCHAR(255),
                           phone_number VARCHAR(255)
);

-- Create resident table
CREATE TABLE resident (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          active BOOLEAN NOT NULL,
                          phone_number VARCHAR(255),
                          CONSTRAINT uc_resident_email UNIQUE (email)
);

-- Create resident_community table
CREATE TABLE resident_community (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    resident_id BIGINT NOT NULL,
                                    community_id BIGINT NOT NULL,
                                    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                    active BOOLEAN NOT NULL,
                                    CONSTRAINT uc_resident_community UNIQUE (resident_id, community_id)
);

-- Create parking_spot table
CREATE TABLE parking_spot (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              version BIGINT NOT NULL,
                              spot_number VARCHAR(255) NOT NULL,
                              community_id BIGINT NOT NULL,
                              status VARCHAR(255) NOT NULL,
                              reserved_by BIGINT,
                              reserved_at TIMESTAMP WITHOUT TIME ZONE,
                              parked_at TIMESTAMP WITHOUT TIME ZONE
);

-- Create parking_history table
CREATE TABLE parking_history (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 resident_community_id BIGINT NOT NULL,
                                 spot_id BIGINT NOT NULL,
                                 reserved_at TIMESTAMP WITHOUT TIME ZONE,
                                 parked_at TIMESTAMP WITHOUT TIME ZONE,
                                 released_at TIMESTAMP WITHOUT TIME ZONE
);

-- Add Foreign Keys

ALTER TABLE resident_community
    ADD CONSTRAINT fk_resident_community_resident
        FOREIGN KEY (resident_id) REFERENCES resident(id);

ALTER TABLE resident_community
    ADD CONSTRAINT fk_resident_community_community
        FOREIGN KEY (community_id) REFERENCES community(id);

ALTER TABLE parking_spot
    ADD CONSTRAINT fk_parking_spot_community
        FOREIGN KEY (community_id) REFERENCES community(id);

ALTER TABLE parking_spot
    ADD CONSTRAINT fk_parking_spot_reserved_by
        FOREIGN KEY (reserved_by) REFERENCES resident_community(id);

ALTER TABLE parking_history
    ADD CONSTRAINT fk_parking_history_resident_community
        FOREIGN KEY (resident_community_id) REFERENCES resident_community(id);

ALTER TABLE parking_history
    ADD CONSTRAINT fk_parking_history_spot
        FOREIGN KEY (spot_id) REFERENCES parking_spot(id);

CREATE INDEX idx_resident_community_resident_id ON resident_community(resident_id);
CREATE INDEX idx_resident_community_community_id ON resident_community(community_id);
CREATE INDEX idx_parking_spot_community_id ON parking_spot(community_id);
CREATE INDEX idx_parking_spot_status ON parking_spot(status);
